---

# Travis configuration

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

env:
  matrix:
    - TOXENV='py27-ansible20-org'
    - TOXENV='py27-ansible20-enterprise'
    - TOXENV='py27-ansible21-org'
    - TOXENV='py27-ansible21-enterprise'
    - TOXENV='py27-ansible22-org'
    - TOXENV='py27-ansible22-enterprise'
    - TOXENV='py27-ansible23-org'
    - TOXENV='py27-ansible23-enterprise'
    - TOXENV='py27-ansible-devel-org'
    - TOXENV='py27-ansible-devel-enterprise'

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine'

install:
  - 'pip install tox-travis'

script:
  - 'tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
