---

ansible_groups:
  org:
    - 'mongodb-org-trusty'
    - 'mongodb-org-xenial'
  enterprise:
    - 'mongodb-ent-trusty'
    - 'mongodb-ent-xenial'

ansible_playbooks:
  - 'testing_deployment.yml'

vagrant_provider: 'virtualbox'
vagrant_synced_folder_type: 'virtualbox'

vagrant_servers:
  - name: 'mongodb-org-trusty'
    box: 'ubuntu/trusty64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
  - name: 'mongodb-org-xenial'
    box: 'ubuntu/xenial64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
  - name: 'mongodb-ent-trusty'
    box: 'ubuntu/trusty64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
  - name: 'mongodb-ent-xenial'
    box: 'ubuntu/xenial64'
    cpus: 1
    family: 'debian'
    forwarded_port: []
    memory: 512
