---

# Debian family installation tasks

- name: 'INSTALL | APT | Install dependencies'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
  loop: "{{ mongodb_dependencies }}"


- name: 'INSTALL | APT | Add GPG key'
  apt_key:
    id: "{{ item.id | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mongodb_gpg_keys }}"


- name: 'INSTALL | APT | Configure repository'
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mongodb_repositories }}"


- name: 'INSTALL | APT | Install "pymongo"'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
  loop: "{{ mongodb_os_packages_pymongo }}"
  when: "mongodb_install_pymongo_method == 'os'"


- name: 'INSTALL | PIP | Install pymongo'
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ mongodb_pip_packages_pymongo }}"
  when: "mongodb_install_pymongo_method == 'pip'"


- name: 'INSTALL | APT | Install all packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
    force: "{{ mongodb_apt_force }}"
  notify: 'Restart all mongo instances'
  loop: "{{ mongodb_packages_all }}"
  when: 'mongodb_install_all'


- name: 'INSTALL | APT | Install server packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
    force: "{{ mongodb_apt_force }}"
  notify: 'Restart all mongod instances'
  loop: "{{ mongodb_packages_server }}"
  when:
    - 'not mongodb_install_all'
    - 'mongodb_install_server'


- name: 'INSTALL | APT | Install mongos packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
    force: "{{ mongodb_apt_force }}"
  notify: 'Restart all mongos instances'
  loop: "{{ mongodb_packages_mongos }}"
  when:
    - 'not mongodb_install_all'
    - 'mongodb_install_mongos'


- name: 'INSTALL | APT | Install shell packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
    force: "{{ mongodb_apt_force }}"
  loop: "{{ mongodb_packages_shell }}"
  when:
    - 'not mongodb_install_all'
    - 'mongodb_install_shell'


- name: 'INSTALL | APT | Install tools packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ mongodb_apt_update_cache }}"
    cache_valid_time: "{{ mongodb_apt_cache_valid_time }}"
    force: "{{ mongodb_apt_force }}"
  loop: "{{ mongodb_packages_tools }}"
  when:
    - 'not mongodb_install_all'
    - 'mongodb_install_tools'
