---

# Main tasks file for mongodb role

- name: 'INIT | Manage variables to use for our target'
  include: 'manage_variables.yml'


- name: 'INSTALL | Manage installation tasks for your OS family'
  become: True
  include: "install_{{ ansible_os_family | lower }}.yml"


- name: 'CONFIG | Manage default instance'
  become: True
  include: 'manage_default_instance.yml'


- name: 'CONFIG | Manage user instances'
  become: True
  include: 'manage_user_instances.yml'


- name: 'CONFIG | Manage services'
  become: True
  include: 'manage_services.yml'


- name: 'CONFIG | Restart instance if change occured'
  become: True
  service:
    name: "{{ item.0.item.type }}_{{ item.0.item.config.net.port }}"
    state: 'restarted'
  with_together:
    - "{{ mongodb_check_configuration_files.results }}"
    - "{{ mongodb_check_upstart_files.results }}"
    - "{{ mongodb_check_systemd_files.results }}"
  when:
    - "{{ item.0.changed or item.1.changed or item.2.changed }}"
    - "{{ (item.0.item.state | default('present')) == 'present' }}"
    - "{{ item.0.item.enabled | default(True) }}"
